name: nexus_erp_pro
description: Nexus ERP Pro - Universal Multi-Plataforma con Motor Fiscal SENIAT, Integridad Financiera y Supabase Cloud Sync
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase Cloud Backend
  supabase_flutter: ^2.5.0

  # Base de Datos Local y Encriptación
  sqflite_sqlcipher: ^3.1.0
  path: ^1.9.0
  crypto: ^3.0.3
  http: ^1.2.0

  # Finanzas / Precisión Contable
  decimal: ^2.3.3


  # Hardware: Lectura NFC / Contactless
  nfc_manager: ^3.3.0

  # Hardware: Conexión con Impresoras y Puntos de Venta (Serial RS-232 / USB / Bluetooth)
  flutter_libserialport: ^0.4.0
  blue_thermal_printer: ^1.2.3

  # Utilidades
  intl: ^0.19.0
  uuid: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
